Feature/add gakku
Code-for-Funabashi/open-data-parser pull request #17
Opened 2021-09-22 08:14 UTC by Jumpo-523

2021-09-22 08:18 UTC, Jumpo-523 commented on open_data_parser/main.py
> +    # shutil.rmtree(OUTPUT_BASE_PATH)
すいません、rmtreeコメントアウトしたままでした。

2021-09-24 07:14 UTC, aca-ta requested changes
コメントしました。

2021-09-24 07:14 UTC, aca-ta commented on open_data_parser/transformer.py
> +def shapeRecord2dict(
transformerは情報の加工を行う機能のイメージで作りました。
この関数の役割はデータ形式の変更で、readerかformatterに設定した方が自然な気がしましたがいかがでしょう。

2021-09-24 07:14 UTC, aca-ta commented on open_data_parser/main.py
> +from open_data_parser.downloader import fetch_csv, read_csv, read_shapefile
他のモジュールに合わせて、1行1モジュールのimportにした方が良いかなと思いました。
特にどちらが正しいというのはないですが、個人的にはこの方がエラーメッセージが読みやすいので好きです。

2021-09-24 07:14 UTC, aca-ta commented on open_data_parser/downloader.py
> +def read_shapefile(path: str) -> Iterator[shapefile.ShapeRecord]:
shapefile自体のダウンロードは手動で行う設計だと思いますが、なにか理由はありますか？

2021-09-24 07:14 UTC, aca-ta commented on open_data_parser/downloader.py
> +    localに配置させたcsv fileからデータを読み込み、
コメントが正しくないと思います。

2021-09-26 02:12 UTC, Jumpo-523 commented on open_data_parser/transformer.py
> +def shapeRecord2dict(
>transformerは情報の加工を行う機能
認識は共有させて頂いていたかなと思っております。
readしたshapefileの属性情報の加工処理が入るという観点からtransformerにしてました。
(下記で行っているような処理
```
                schema={
                    "name": ["A27_006", "A27_007"],
                    "inst_subject": ["A27_006"],
                    "address": ["A27_008"]
                }

```
)
まぁでもおっしゃる通り、メインの役割はデータ形式の変更と考えるとreaderに持たせる方がいいかもと思ってきました。

2021-09-26 02:12 UTC, Jumpo-523 commented on open_data_parser/transformer.py
> +
ありがとうございます。習慣化します。

2021-09-26 03:36 UTC, aca-ta commented on open_data_parser/transformer.py
> +    reset_order_to_latlon = lambda lon_lat: lon_lat[::-1]
`list(map(coord[::-1], coordinates))` じゃだめなんでしたっけ？

2021-09-26 03:38 UTC, aca-ta commented on open_data_parser/downloader.py
> +def read_shapefile(path: str) -> Iterator[shapefile.ShapeRecord]:
都度ダウンロードした方が良いかなと思いますが、しない理由はありますか？

2021-09-26 03:42 UTC, aca-ta commented on open_data_parser/transformer.py
> +    reset_order_to_latlon = lambda lon_lat: lon_lat[::-1]
あ、ダメですね。失礼しました。

2021-09-26 11:33 UTC, Jumpo-523 commented on open_data_parser/downloader.py
> +def read_shapefile(path: str) -> Iterator[shapefile.ShapeRecord]:
m__m, ないですね、直接HPから取ってきた方がレポジトリ余分に重くならないし、修正します！

2021-09-26 13:17 UTC, aca-ta commented
そういえば、新設された塚田南小学校の学区は乗ってないですね。
元データが2010年度版で、おそらくネット上に最新のデータは転がっていないため、本気でやるなら[このページ](https://www.city.funabashi.lg.jp/kodomo/ichiritsu/004/p008673.html) からポリゴンを作るなどしないといけないと思いますが、、

2021-09-26 13:26 UTC, Jumpo-523 commented on open_data_parser/transformer.py
> +def shapeRecord2dict(
formatterまで、key書き換え処理いらないかもなと思い始めました。
downloaderで下記の情報を抽出してdictにした上で、
transformerで"A27_006"キーを用いた地物filtering処理、
最後にformatterで’name’整形するのが自然かもしれませんね

downloader.download_shapefile（仮名）で得られるDict要素
```py
{
'A27_005': '12204', 
'A27_006': '船橋市立', 
'A27_007': '海神小学校', 
'A27_008': '船橋市海神2-6-5',
'coordinates': [[lon, lat], [lon, lat]...[lon, lat]],
}
```

2021-09-26 13:33 UTC, Jumpo-523 commented
ありがとうございます！
なるほど、一学区だけでしたら全然ありですね。（ただ、X丁目Y番地まで細かいpolygonデータなかったような気がしています、、、笑ご存知でしたら教えてください！！m__m）

とりあえず急務かどうかはさておき、放置したくもないので、issueとして追加しておきます！

2021-10-04 12:05 UTC, Jumpo-523 reviewed
大きな改修ポイント
- hole付きポリゴンデータを正しく読み込めるように修正しました。
- fetch_shapefileでzipファイルをダウンロードし、schemeを指定できる関数を作成しました。
- コメントいただいた部分修正しました。

2021-10-05 14:02 UTC, aca-ta requested changes
コメントしました。

2021-10-05 14:02 UTC, aca-ta commented on open_data_parser/transformer.py
> +
うーん、素直にマルチポリゴンを使えるshapelyを使った方が良いような、、

2021-10-06 01:52 UTC, Jumpo-523 commented on open_data_parser/transformer.py
> +
なるほど、、ちょっとshapely調査してみます。

2021-11-27 02:00 UTC, j-takurou commented on tests/test_downloader.py
> +""" test for downloader.py """
ディレクトリ配置修正しました

2021-11-27 02:12 UTC, j-takurou commented
遅くなりました！m_m

1. 以下のように関数分割して、test_downloader.pyに2つテスト追加しました。
- unzipしてshapefileレコードを出力する関数
- Keyの名前を修正する関数
2. shapely moduleのmapping / shape関数を利用し、exteriorとholeを分けて正しい座標リスト形式にできるようにしました。

2021-11-28 13:04 UTC, aca-ta reviewed
2点だけご確認お願いします。

2021-12-05 13:07 UTC, j-takurou commented on pyproject.toml
> +pyshp = "^2.1.3"
pyshp moduleは、unzip_shapefile関数で shapefile readするのに利用しているので残します。

2021-12-05 13:12 UTC, aca-ta commented on open_data_parser/downloader.py
> +    args:
```
    Args:
        data: Dict
            example: {"A": "val_a", "B": "val_b"}
        new_schema: Dict
            new_schema = {"AB": ["A", "B"]}
    Returns:
            Dict:
                example: {"AB": "val_a val_b"}

```

2021-12-05 13:49 UTC, j-takurou commented on open_data_parser/downloader.py
> +    args:
ありがとうございます。こちら対応いたしました！
https://github.com/Code-for-Funabashi/open-data-parser/blob/090e1843f1d85e577a9bb4cd0cc5c2c665f79017/open_data_parser/downloader.py

2021-12-05 14:46 UTC, aca-ta approved these changes
修正ありがとうございました！
LGTMです！

2021-12-13 14:12 UTC, j-takurou commented
こちらこそありがとうございます！！

2021-12-13 14:12 UTC, merged