2022年12月データを反映
Code-for-Funabashi/open-data-parser pull request #25
Opened 2022-10-20 14:49 UTC by aca-ta

# 背景
2022年12月分データが公開されたので、子育てマップ用のデータを更新する。

2022-10-20 14:50 UTC, aca-ta commented on open_data_parser/main.py
> +            usecols="F,I:N",
エクセルフォーマットの変更に対応

2022-10-22 03:25 UTC, j-takurou requested changes
12月分の「家庭的保育事業者」が三件に減っているので、skipfooter=3にしないと小室の保育園の
情報が消えちゃうかもです。

2022-10-22 07:52 UTC, j-takurou approved these changes
ご確認・改修有難うございます！

2022-10-22 07:52 UTC, aca-ta commented
@j-takurou 
指摘ありがとうございます！
修正しました :bow:

2022-10-22 07:53 UTC, aca-ta commented
レビューありがとうございました、マージします！

2022-10-22 07:53 UTC, merged